[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "axialfans"
version = "0.1.0"
description = "Analytical solver for multistage ducted axial fans."
authors = [
  { name="Sean Wang", email="you@example.com" }
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["numpy>=1.23"]