[build-system]
requires = ["setuptools>=65", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "axialfans"
version = "1.0.0"
description = "Analytical solver for multistage ducted axial fans."
authors = [
  { name = "Sean H. Wang", email = "seanwangpiano@gmail.com" }
]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numpy>=1.23"
]

[project.urls]
"Homepage" = "https://github.com/sean-h-wang/axialfans"
"Documentation" = "https://github.com/sean-h-wang/axialfans#readme"
