[metadata]
name = axialfans
version = 2.0.0
author = Sean H. Wang
author_email = seanwangpiano@gmail.com
description = Spanwise-resolved analytical solver for multistage axial turbomachinery
long_description = file: README.md
long_description_content_type = text/markdown
license = MIT
license_files = LICENSE
url = https://github.com/sean-h-wang/axialfans
classifiers =
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent
    Topic :: Scientific/Engineering
    Topic :: Scientific/Engineering :: Physics

[options]
packages = find:
python_requires = >=3.9
install_requires =
    numpy>=1.23

[options.package_data]
* = *.md